### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by kevingelion** [inderps/hyperterm-find-text-onscreen#1]
```
bundle.js:661 Error: Cannot find module '/Users/kevin/.hyper_plugins/node_modules/hyperterm-find-text-onscreen'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/Applications/Hyper.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at require (internal/module.js:20:19)
    at paths.plugins.concat.map.err (file:///Applications/Hyper.app/Contents/Resources/app/dist/bundle.js:659:20)
    at Array.map (native)
    at loadModules (file:///Applications/Hyper.app/Contents/Resources/app/dist/bundle.js:652:54)
    at Object.<anonymous> (file:///Applications/Hyper.app/Contents/Resources/app/dist/bundle.js:757:1)
    at __webpack_require__ (file:///Applications/Hyper.app/Contents/Resources/app/dist/bundle.js:20:30)
    at Object.<anonymous> (file:///Applications/Hyper.app/Contents/Resources/app/dist/bundle.js:50910:73)
```

**Comment by inderps** [comment]
I'm sorry, it is still in progress

Not usable
